### ISSUE TITLE
Wallet isn't updating funds

### ISSUE THREAD

**Issue by Earendil137** [masari-project/masari-webwallet#17]
Hey, so I transferred sometimes to my wallet after mining, but the wallet is still not reflecting it. It's still showing empty.

**Comment by gnock** [comment]
Can you check that the address to where you send your fund is the one loaded in the webwallet ? Also, is the webwallet fully synchronized ?
Also, verify the transaction is in the blockchain by searching on https://msrchain.net

If you have trouble and need more support, as lot of people are using it without troubles, please contact us on the channel #support of the official discord (https://discord.gg/eSb9ZdM)

**Comment by Earendil137** [comment]
I rechecked based on your suggestion.
https://msrchain.net/search?value=06c3b9ecc4e52e8d22c111c1cb664f7553a523b7efaf7e09dc793372b5665f20

But I still haven't got the amount I mined.
I was mining through hashvault.
The wallet address I entered there is correct as per the address shown in the Masari Web Wallet.

**Comment by gnock** [comment]
The deployed patch is not working anymore.
See #26 to keep track of the bug
